server:
  port: 9090

spring:
  application:
    name: booking

  cloud:
    function:
      definition: persistUserInBookingDB;acceptBooking
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        persistUserInBookingDB-in-0:
          destination: "user-registration"
          group: ${spring.application.name}
        send-booking-out-0:
          destination: "send-booking"
        acceptBooking-in-0:
          destination: "accept-booking"
          group: ${spring.application.name}

  datasource:
#    url: jdbc:h2:mem:uberdb
    url: jdbc:mysql://localhost:3306/uberdb
    username: root
    password: root


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  h2:
    console:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8181/eureka

info:
  app:
    name: ${spring.application.name}
    description: "booking-application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true