spring:
  cloud:

    function:
      definition: fetchBooking;addDriver
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        fetchBooking-in-0:
          destination: "send-booking"
          group: ${spring.application.name}
        addDriver-in-0:
          destination: "user-registration"
          group: ${spring.application.name}
        accept-booking-out-1:
          destination: "accept-booking"



  application:
    name: driver

  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:mysql://localhost:3307/uberdb
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  h2:
#    console:
#      enabled: true

  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8181/eureka

info:
  app:
    name: ${spring.application.name}
    description: "driver-application"
    version: "1.0.0"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true